alias a="vim ~/.bash_aliases"
alias dotfiles="git --git-dir=$HOME/dotfiles.git --work-tree=$HOME"
alias e="vim"
alias i="vim ~/.config/i3/config"
alias m="make"
alias o="xdg-open"
alias pj="vim -c \"if filereadable('proj.vim') | source proj.vim | endif \""
alias soba="source ~/.bash_aliases"
alias tree="tree -I \"__pycache__|node_modules\""
alias u="vim ~/.Xresources"
alias v="vim ~/.vim/vimrc"
alias ww="vim ~/vimwiki/index.wiki"
