alias e="vim"
alias a="vim ~/.bash_aliases"
alias tree="tree -I \"__pycache__|node_modules\""
alias soba="source ~/.bash_aliases"
alias pj="vim -c \"if filereadable('proj.vim') | source proj.vim | endif \""
alias v="vim ~/.vim/vimrc"
alias m="make"
alias u="vim ~/.Xresources"
alias ww="vim ~/vimwiki/index.wiki"
alias dotfiles="git --git-dir=$HOME/dotfiles.git --work-tree=$HOME"
alias i="vim ~/.config/i3/config"
