alias e="vim"
alias a="vim ~/.bash_aliases"
alias tree="tree -I \"__pycache__|node_modules\""
alias soba="source ~/.bash_aliases"
alias pj="vim -c \"if filereadable('proj.vim') | source proj.vim | endif \""
alias v="vim ~/.vim/vimrc"
alias m="make"
alias k="vim ~/.config/kitty/kitty.conf"
alias u="vim ~/.Xresources"
alias t="vim ~/.tmux.conf"
alias ww="vim ~/vimwiki/index.wiki"
alias dotfiles="git --git-dir=$HOME/dotfiles.git --work-tree=$HOME"
alias obrc="vim ~/.config/openbox/rc.xml"
alias obme="vim ~/.config/openbox/menu.xml"
alias obas="vim ~/.config/openbox/autostart"
alias tint="vim ~/.config/tint2/tint2rc"
alias i="vim ~/.config/i3/config"
